sudo: required
services:
  - docker

before_install:
  - docker build -t luisperez992/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run luisperez992/react-test npm test -- --coverage

after_success:
  - docker build -t luisperez992/multi-client ./client
  - docker build -t luisperez992/multi-nginx ./nginx
  - docker build -t luisperez992/multi-server ./server
  - docker build -t luisperez992/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luisperez992/multi-client
  - docker push luisperez992/multi-nginx
  - docker push luisperez992/multi-server
  - docker push luisperez992/multi-worker

